#!/bin/bash

echo "Enter project name:"
read input

PROJECT_DIR="attendance_tracker_${input}"

cleanup() {
    echo "Script interrupted! Archiving current state..."
    tar -czf "attendance_tracker_${input}_archive.tar.gz" "${PROJECT_DIR}" 2>/dev/null
    rm -rf "${PROJECT_DIR}"
    echo "Archive created and incomplete directory removed."
    exit 1
}

trap cleanup SIGINT

mkdir -p "${PROJECT_DIR}/Helpers"
mkdir -p "${PROJECT_DIR}/reports"

cat > "${PROJECT_DIR}/Helpers/assets.csv" <<EOF
Email,Names,Attendance Count,Absence Count
alice@example.com,Alice Johnson,14,1
bob@example.com,Bob Smith,7,8
charlie@example.com,Charlie Davis,4,11
diana@example.com,Diana Prince,15,0
EOF

cat > "${PROJECT_DIR}/Helpers/config.json" <<EOF
{
  "thresholds": {
    "warning": 75,
    "failure": 50
  },
  "run_mode": "live",
  "total_sessions": 15
}
EOF

cat > "${PROJECT_DIR}/reports/reports.log" <<EOF
--- Attendance Report Log ---
Generated by setup_project.sh
EOF

cat > "${PROJECT_DIR}/attendance_checker.py" <<'EOF'
import csv
import json
import os
from datetime import datetime

def run_attendance_check():
    with open('Helpers/config.json', 'r') as f:
        config = json.load(f)

    if os.path.exists('reports/reports.log'):
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        os.rename('reports/reports.log', f'reports/{timestamp}.log.archive')

    with open('Helpers/assets.csv', mode='r') as f, open('reports/reports.log', 'w') as log:
        reader = csv.DictReader(f)
        total_sessions = config['total_sessions']

        log.write(f"--- Attendance Report Run: {datetime.now()} ---\n")

        for row in reader:
            name = row['Names']
            email = row['Email']
            attended = int(row['Attendance Count'])

            attendance_pct = (attended / total_sessions) * 100

            message = ""
            if attendance_pct < config['thresholds']['failure']:
                message = f"URGENT: {name}, your attendance is {attendance_pct:.1f}%. You will fail this class."
            elif attendance_pct < config['thresholds']['warning']:
                message = f"WARNING: {name}, your attendance is {attendance_pct:.1f}%. Please be careful."

            if message:
                if config['run_mode'] == "live":
                    log.write(f"[{datetime.now()}] ALERT SENT TO {email}: {message}\n")
                    print(f"Logged alert for {name}")
                else:
                    print(f"[DRY RUN] Email to {email}: {message}")

if __name__ == "__main__":
    run_attendance_check()
EOF

echo "Do you want to update attendance thresholds? (yes/no):"
read update_choice

if [ "$update_choice" == "yes" ]; then
    echo "Enter new Warning threshold (default 75):"
    read warning_val
    echo "Enter new Failure threshold (default 50):"
    read failure_val

    sed -i "s/\"warning\": [0-9]*/\"warning\": ${warning_val}/" "${PROJECT_DIR}/Helpers/config.json"
    sed -i "s/\"failure\": [0-9]*/\"failure\": ${failure_val}/" "${PROJECT_DIR}/Helpers/config.json"

    echo "Thresholds updated successfully!"
fi

echo "--- Health Check ---"
if command -v python3 &>/dev/null; then
    echo "Python3 is installed: $(python3 --version)"
else
    echo "WARNING: Python3 is not installed on this system!"
fi

echo "--- Verifying Directory Structure ---"
if [ -f "${PROJECT_DIR}/attendance_checker.py" ] && \
   [ -f "${PROJECT_DIR}/Helpers/config.json" ] && \
   [ -f "${PROJECT_DIR}/Helpers/assets.csv" ] && \
   [ -f "${PROJECT_DIR}/reports/reports.log" ]; then
    echo "Directory structure verified successfully!"
else
    echo "WARNING: Some files are missing!"
fi

echo "Project setup complete!"
